# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ctbb_treballs_jardineria
                                 A QGIS plugin
 Incidencies de CTBB Treballs Jardineria
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-28
        copyright            : (C) 2024 by Gerald Kogler
        email                : geraldo@servus.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ctbb_treballs_jardineria class from file ctbb_treballs_jardineria.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ctbb_treballs_jardineria import ctbb_treballs_jardineria
    return ctbb_treballs_jardineria(iface)
